export const products = [
  // 🔥 Trending Toys
  {
    id: 1,
    name: 'Superhero Action Figure',
    price: 800,
    category: 'Action',
    categoryTag: 'trending',
    rating: 4.5,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Xudl0b-Rne0vI7e-NNrKN223Et_souKWTw&s',
    description: 'A powerful superhero figure for kids to play and imagine adventures.',
  },
  {
    id: 2,
    name: 'Remote Control Car',
    price: 1500,
    category: 'Electronics',
    categoryTag: 'trending',
    rating: 4.7,
    image:
      'https://electrobotic.in/cdn/shop/files/8wheelsrccarremotecontrolcar8wheelsyellowcolour4wd.jpg?v=1694525756',
    description: 'High-speed RC car with rechargeable battery and durable body.',
  },
  {
    id: 3,
    name: 'Talking Doll',
    price: 1200,
    category: 'Dolls',
    categoryTag: 'trending',
    rating: 4.2,
    image:
      'https://images-cdn.ubuy.co.in/656bd1ac89cc767c9761418a-little-darling-talking-baby-3114-12.jpg',
    description: 'Cute doll that talks and sings nursery rhymes.',
  },
  {
    id: 4,
    name: 'Lego Classic Set',
    price: 2500,
    category: 'Educational',
    categoryTag: 'trending',
    rating: 4.9,
    image:
      'https://cdn.pixelbin.io/v2/black-bread-289bfa/HrdP6X/original/hamleys-product/494376884/665/494376884-1_5715.webp',
    description: 'Creative building blocks set with 500+ colorful bricks.',
  },
  {
    id: 5,
    name: 'Mini Drone',
    price: 3500,
    category: 'Electronics',
    categoryTag: 'trending',
    rating: 4.6,
    image:
      'https://www.designinfo.in/wp-content/uploads/2024/07/IZI-PRO-Nano-Drone-720P-HD-Camera-1.webp',
    description: 'Small, easy-to-fly drone for kids with camera and remote control.',
  },
  {
    id: 6,
    name: 'Football Play Set',
    price: 700,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.3,
    image: 'https://m.media-amazon.com/images/I/41M7EwquDSL._UF1000,1000_QL80_.jpg',
    description: 'Durable football set for kids with mini goalpost.',
  },
  {
    id: 7,
    name: 'Wooden Train Set',
    price: 1000,
    category: 'Classic Toys',
    categoryTag: 'trending',
    rating: 4.4,
    image: 'https://m.media-amazon.com/images/I/81XsmUmi9HL._UF1000,1000_QL80_.jpg',
    description: 'Colorful wooden train track set with wagons.',
  },
  {
    id: 8,
    name: 'Puzzle Cube',
    price: 300,
    category: 'Brain Games',
    categoryTag: 'trending',
    rating: 4.1,
    image:
      'https://media.ipassio.com/media/blog/benefits-of-solving-rubiks-cube/blog_icon/benefits-of-solving-rubiks-cube.jpg',
    description: 'Fun 3D puzzle cube for problem solving and creativity.',
  },
  {
    id: 9,
    name: 'Basketball Hoop Set',
    price: 1800,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/71ceekDSzZL._UF894,1000_QL80_.jpg',
    description: 'Indoor mini basketball hoop for kids with ball included.',
  },
  {
    id: 10,
    name: 'Magic Kit',
    price: 950,
    category: 'Educational',
    categoryTag: 'trending',
    rating: 4.0,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXhfRtundq1CFUQQlqpe1-yHGTm7IQvUqwKQ&s',
    description: 'Beginner’s magic trick kit to entertain and learn.',
  },

  // 🆕 Latest Toys
  {
    id: 11,
    name: 'Robot Dog',
    price: 2200,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.8,
    image: 'https://m.media-amazon.com/images/I/61aLnSfQfJL.jpg',
    description: 'Smart interactive robotic dog that responds to touch and sound.',
  },
  {
    id: 12,
    name: 'Glow in the Dark Slime Kit',
    price: 400,
    category: 'DIY',
    categoryTag: 'latest',
    rating: 4.3,
    image: 'https://m.media-amazon.com/images/I/81g3iDFgPgL.jpg',
    description: 'Make your own glowing slime with safe, non-toxic materials.',
  },
  {
    id: 13,
    name: 'Musical Keyboard',
    price: 3000,
    category: 'Music',
    categoryTag: 'latest',
    rating: 4.6,
    image: 'https://m.media-amazon.com/images/I/71NYfBA5kLL.jpg',
    description: 'Mini keyboard with songs, beats, and record option for kids.',
  },
  {
    id: 14,
    name: 'Remote Helicopter',
    price: 2800,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.7,
    image:
      'https://images-cdn.ubuy.co.in/633b4c355e15d131c8151e45-cheerwing-u12s-mini-rc-helicopter-with.jpg',
    description: 'Easy-to-fly RC helicopter with strong stability.',
  },
  {
    id: 15,
    name: 'Mini Kitchen Set',
    price: 850,
    category: 'Role Play',
    categoryTag: 'latest',
    rating: 4.2,
    image: 'https://m.media-amazon.com/images/I/61QpBPnwYsL.jpg',
    description: 'Colorful kitchen play set with utensils and food items.',
  },
  {
    id: 16,
    name: 'Spider Robot',
    price: 1800,
    category: 'Educational',
    categoryTag: 'latest',
    rating: 4.4,
    image: 'https://m.media-amazon.com/images/I/71GDf4GVQiL.jpg',
    description: 'STEM learning kit where kids can build their own spider robot.',
  },
  {
    id: 17,
    name: 'Bubble Machine',
    price: 600,
    category: 'Outdoor',
    categoryTag: 'latest',
    rating: 4.1,
    image: 'https://m.media-amazon.com/images/I/61ueEMvbcCL.jpg',
    description: 'Automatic bubble machine with refill liquid included.',
  },
  {
    id: 18,
    name: 'Dinosaur Toy Set',
    price: 1400,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/81jro9MhceL.jpg',
    description: 'Set of 6 realistic dinosaur figures with details.',
  },
  {
    id: 19,
    name: 'Drone with VR',
    price: 5000,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.9,
    image: 'https://i.3dmodels.org/uploads/evermotion/784_AM261_32/AM261_32_1000_0001.jpg',
    description: 'VR-enabled drone with immersive flying experience.',
  },
  {
    id: 20,
    name: 'RC Monster Truck',
    price: 3200,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.6,
    image: 'https://m.media-amazon.com/images/I/8134eChN7nL.jpg',
    description: 'All-terrain monster truck with remote control and big wheels.',
  },

  // 🏆 Best Selling Toys
  {
    id: 21,
    name: 'Soft Teddy Bear',
    price: 500,
    category: 'Soft Toys',
    categoryTag: 'best',
    rating: 4.9,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7Vo28Pgg3_lEpVyEFvww8MghOyoi8DeZTHA&s',
    description: 'Cute and cuddly teddy bear – a timeless favorite.',
  },
  {
    id: 22,
    name: 'Uno Card Game',
    price: 250,
    category: 'Games',
    categoryTag: 'best',
    rating: 4.8,
    image:
      'https://rukminim2.flixcart.com/image/704/844/xif0q/card-game/v/w/r/3-uno-original-vs-uno-flip-card-games-classic-colour-number-original-imagq9qsytphezub.jpeg?q=90&crop=false',
    description: 'Classic family card game of colors and numbers.',
  },
  {
    id: 23,
    name: 'Chess Set',
    price: 650,
    category: 'Brain Games',
    categoryTag: 'best',
    rating: 4.7,
    image:
      'https://www.jiomart.com/images/product/original/rvy1gnqe4c/enorme-magnetic-educational-folding-chess-board-game-for-kids-and-adults-10-inch-product-images-orvy1gnqe4c-p591419318-0-202205180647.jpg?im=Resize=(420,420)',
    description: 'Wooden chess board set for strategy lovers.',
  },
  {
    id: 24,
    name: 'Rubber Duck',
    price: 150,
    category: 'Bath Toys',
    categoryTag: 'best',
    rating: 4.3,
    image:
      'https://toyshine.in/cdn/shop/products/1_e18b862c-7fd6-486c-abb4-43f7ae332a5c.jpg?v=1546947786',
    description: 'Yellow rubber duck for fun bath time.',
  },
  {
    id: 25,
    name: 'Toy Guitar',
    price: 700,
    category: 'Music',
    categoryTag: 'best',
    rating: 4.4,
    image:
      'https://images-cdn.ubuy.co.in/642429b22c20c26afd62fa26-vokodo-toy-guitar-6-metal-string.jpg',
    description: 'Mini guitar toy with sound effects.',
  },
  {
    id: 26,
    name: 'Board Game - Snakes & Ladders',
    price: 350,
    category: 'Games',
    categoryTag: 'best',
    rating: 4.6,
    image:
      'https://images-cdn.ubuy.co.in/66b5d3e570fe6e2bec674f40-snakes-ladders-game-for-kids-ages-3.jpg',
    description: 'Classic board game for family fun.',
  },
  {
    id: 27,
    name: 'Toy Doctor Kit',
    price: 950,
    category: 'Role Play',
    categoryTag: 'best',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/810KM6rPQ1L.jpg',
    description: 'Doctor role play kit with stethoscope and medical tools.',
  },
  {
    id: 28,
    name: 'Mini Cricket Set',
    price: 1100,
    category: 'Sports',
    categoryTag: 'best',
    rating: 4.6,
    image: 'https://5.imimg.com/data5/OF/BM/BT/SELLER-31885063/miniature-cricket-set-500x500.jpg',
    description: 'Kids’ cricket set with bat, ball, and stumps.',
  },
  {
    id: 29,
    name: 'RC Speed Boat',
    price: 2800,
    category: 'Electronics',
    categoryTag: 'best',
    rating: 4.7,
    image:
      'https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/60/12/736ee4cc-13a0-413a-b7f9-c54d9bce7b25.jpg.webp',
    description: 'Fast remote-controlled boat for pool and lake fun.',
  },
  {
    id: 30,
    name: 'Play Dough Kit',
    price: 450,
    category: 'DIY',
    categoryTag: 'best',
    rating: 4.5,
    image:
      'https://rukminim2.flixcart.com/image/704/844/kox8b680/art-craft-kit/0/c/o/1-set-of-play-dough-modeling-clay-6-colours-of-50-gram-each-with-original-imag39vys9gmywyg.jpeg?q=90&crop=false',
    description: 'Colorful clay set for kids to shape and play.',
  },
]
