export const products = [
  // 🔥 Trending Toys
  {
    id: 1,
    name: 'Superhero Action Figure',
    price: 800,
    category: 'Action',
    categoryTag: 'trending',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Xudl0b-Rne0vI7e-NNrKN223Et_souKWTw&s',
    description: 'A powerful superhero figure for kids to play and imagine adventures.',
  },
  {
    id: 2,
    name: 'Remote Control Car',
    price: 1500,
    category: 'Electronics',
    categoryTag: 'trending',
    rating: 4.7,
    isFavourite: false,
    image:
      'https://electrobotic.in/cdn/shop/files/8wheelsrccarremotecontrolcar8wheelsyellowcolour4wd.jpg?v=1694525756',
    description: 'High-speed RC car with rechargeable battery and durable body.',
  },
  {
    id: 3,
    name: 'Talking Doll',
    price: 1200,
    category: 'Dolls',
    categoryTag: 'trending',
    rating: 4.2,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/656bd1ac89cc767c9761418a-little-darling-talking-baby-3114-12.jpg',
    description: 'Cute doll that talks and sings nursery rhymes.',
  },
  {
    id: 4,
    name: 'Lego Classic Set',
    price: 2500,
    category: 'Educational',
    categoryTag: 'trending',
    rating: 4.9,
    isFavourite: false,
    image:
      'https://cdn.pixelbin.io/v2/black-bread-289bfa/HrdP6X/original/hamleys-product/494376884/665/494376884-1_5715.webp',
    description: 'Creative building blocks set with 500+ colorful bricks.',
  },
  {
    id: 5,
    name: 'Mini Drone',
    price: 3500,
    category: 'Electronics',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://www.designinfo.in/wp-content/uploads/2024/07/IZI-PRO-Nano-Drone-720P-HD-Camera-1.webp',
    description: 'Small, easy-to-fly drone for kids with camera and remote control.',
  },
  {
    id: 6,
    name: 'Football Play Set',
    price: 700,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.3,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/41M7EwquDSL._UF1000,1000_QL80_.jpg',
    description: 'Durable football set for kids with mini goalpost.',
  },
  {
    id: 7,
    name: 'Wooden Train Set',
    price: 1000,
    category: 'Classic Toys',
    categoryTag: 'trending',
    rating: 4.4,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/81XsmUmi9HL._UF1000,1000_QL80_.jpg',
    description: 'Colorful wooden train track set with wagons.',
  },
  {
    id: 8,
    name: 'Puzzle Cube',
    price: 300,
    category: 'Brain Games',
    categoryTag: 'trending',
    rating: 4.1,
    isFavourite: false,
    image:
      'https://img.freepik.com/premium-photo/rubik-cube-with-white-background_1021856-26194.jpg',
    description: 'Fun 3D puzzle cube for problem solving and creativity.',
  },
  {
    id: 9,
    name: 'Basketball Hoop Set',
    price: 1800,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.5,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71ceekDSzZL._UF894,1000_QL80_.jpg',
    description: 'Indoor mini basketball hoop for kids with ball included.',
  },
  {
    id: 10,
    name: 'Magic Kit',
    price: 950,
    category: 'Educational',
    categoryTag: 'trending',
    rating: 4.0,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXhfRtundq1CFUQQlqpe1-yHGTm7IQvUqwKQ&s',
    description: 'Beginner’s magic trick kit to entertain and learn.',
  },

  // 🆕 Latest Toys
  {
    id: 11,
    name: 'Robot Dog',
    price: 2200,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.8,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61aLnSfQfJL.jpg',
    description: 'Smart interactive robotic dog that responds to touch and sound.',
  },
  {
    id: 12,
    name: 'Glow in the Dark Slime Kit',
    price: 400,
    category: 'DIY',
    categoryTag: 'latest',
    rating: 4.3,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/81g3iDFgPgL.jpg',
    description: 'Make your own glowing slime with safe, non-toxic materials.',
  },
  {
    id: 13,
    name: 'Musical Keyboard',
    price: 3000,
    category: 'Music',
    categoryTag: 'latest',
    rating: 4.6,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71NYfBA5kLL.jpg',
    description: 'Mini keyboard with songs, beats, and record option for kids.',
  },
  {
    id: 14,
    name: 'Remote Helicopter',
    price: 2800,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.7,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/633b4c355e15d131c8151e45-cheerwing-u12s-mini-rc-helicopter-with.jpg',
    description: 'Easy-to-fly RC helicopter with strong stability.',
  },
  {
    id: 15,
    name: 'Mini Kitchen Set',
    price: 850,
    category: 'Role Play',
    categoryTag: 'latest',
    rating: 4.2,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61QpBPnwYsL.jpg',
    description: 'Colorful kitchen play set with utensils and food items.',
  },
  {
    id: 16,
    name: 'Spider Robot',
    price: 1800,
    category: 'Educational',
    categoryTag: 'latest',
    rating: 4.4,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71GDf4GVQiL.jpg',
    description: 'STEM learning kit where kids can build their own spider robot.',
  },
  {
    id: 17,
    name: 'Bubble Machine',
    price: 600,
    category: 'Outdoor',
    categoryTag: 'latest',
    rating: 4.1,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61ueEMvbcCL.jpg',
    description: 'Automatic bubble machine with refill liquid included.',
  },
  {
    id: 18,
    name: 'Dinosaur Toy Set',
    price: 1400,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.5,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/81jro9MhceL.jpg',
    description: 'Set of 6 realistic dinosaur figures with details.',
  },
  {
    id: 19,
    name: 'Drone with VR',
    price: 5000,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.9,
    isFavourite: false,
    image: 'https://i.3dmodels.org/uploads/evermotion/784_AM261_32/AM261_32_1000_0001.jpg',
    description: 'VR-enabled drone with immersive flying experience.',
  },
  {
    id: 20,
    name: 'RC Monster Truck',
    price: 3200,
    category: 'Electronics',
    categoryTag: 'latest',
    rating: 4.6,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/8134eChN7nL.jpg',
    description: 'All-terrain monster truck with remote control and big wheels.',
  },

  // 🏆 Best Selling Toys
  {
    id: 21,
    name: 'Soft Teddy Bear',
    price: 500,
    category: 'Soft Toys',
    categoryTag: 'best',
    rating: 4.9,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7Vo28Pgg3_lEpVyEFvww8MghOyoi8DeZTHA&s',
    description: 'Cute and cuddly teddy bear – a timeless favorite.',
  },
  {
    id: 22,
    name: 'Uno Card Game',
    price: 250,
    category: 'Games',
    categoryTag: 'best',
    rating: 4.8,
    isFavourite: false,
    image:
      'https://rukminim2.flixcart.com/image/704/844/xif0q/card-game/v/w/r/3-uno-original-vs-uno-flip-card-games-classic-colour-number-original-imagq9qsytphezub.jpeg?q=90&crop=false',
    description: 'Classic family card game of colors and numbers.',
  },
  {
    id: 23,
    name: 'Chess Set',
    price: 650,
    category: 'Brain Games',
    categoryTag: 'best',
    rating: 4.7,
    isFavourite: false,
    image:
      'https://www.jiomart.com/images/product/original/rvy1gnqe4c/enorme-magnetic-educational-folding-chess-board-game-for-kids-and-adults-10-inch-product-images-orvy1gnqe4c-p591419318-0-202205180647.jpg?im=Resize=(420,420)',
    description: 'Wooden chess board set for strategy lovers.',
  },
  {
    id: 24,
    name: 'Rubber Duck',
    price: 150,
    category: 'Bath Toys',
    categoryTag: 'best',
    rating: 4.3,
    isFavourite: false,
    image:
      'https://toyshine.in/cdn/shop/products/1_e18b862c-7fd6-486c-abb4-43f7ae332a5c.jpg?v=1546947786',
    description: 'Yellow rubber duck for fun bath time.',
  },
  {
    id: 25,
    name: 'Toy Guitar',
    price: 700,
    category: 'Music',
    categoryTag: 'best',
    rating: 4.4,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/642429b22c20c26afd62fa26-vokodo-toy-guitar-6-metal-string.jpg',
    description: 'Mini guitar toy with sound effects.',
  },
  {
    id: 26,
    name: 'Board Game - Snakes & Ladders',
    price: 350,
    category: 'Games',
    categoryTag: 'best',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/66b5d3e570fe6e2bec674f40-snakes-ladders-game-for-kids-ages-3.jpg',
    description: 'Classic board game for family fun.',
  },
  {
    id: 27,
    name: 'Toy Doctor Kit',
    price: 950,
    category: 'Role Play',
    categoryTag: 'best',
    rating: 4.5,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/810KM6rPQ1L.jpg',
    description: 'Doctor role play kit with stethoscope and medical tools.',
  },
  {
    id: 28,
    name: 'Mini Cricket Set',
    price: 1100,
    category: 'Sports',
    categoryTag: 'best',
    rating: 4.6,
    isFavourite: false,
    image: 'https://5.imimg.com/data5/OF/BM/BT/SELLER-31885063/miniature-cricket-set-500x500.jpg',
    description: 'Kids’ cricket set with bat, ball, and stumps.',
  },
  {
    id: 29,
    name: 'RC Speed Boat',
    price: 2800,
    category: 'Electronics',
    categoryTag: 'best',
    rating: 4.7,
    isFavourite: false,
    image:
      'https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/60/12/736ee4cc-13a0-413a-b7f9-c54d9bce7b25.jpg.webp',
    description: 'Fast remote-controlled boat for pool and lake fun.',
  },
  {
    id: 30,
    name: 'Play Dough Kit',
    price: 450,
    category: 'DIY',
    categoryTag: 'best',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://rukminim2.flixcart.com/image/704/844/kox8b680/art-craft-kit/0/c/o/1-set-of-play-dough-modeling-clay-6-colours-of-50-gram-each-with-original-imag39vys9gmywyg.jpeg?q=90&crop=false',
    description: 'Colorful clay set for kids to shape and play.',
  },
  {
    id: 31,
    name: 'Heroic Warrior Action Figure',
    price: 950,
    category: 'Action',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://japanworld.it/106608-large_default/mattel-masters-of-the-universe-teela-heroic-warrior-goddess-cartoon-collection.jpg',
    description: 'A fierce warrior toy ready for epic battles and adventures.',
  },
  {
    id: 32,
    name: 'Turbo Speed Racer Car',
    price: 1200,
    category: 'Cars',
    categoryTag: 'latest',
    rating: 4.8,
    isFavourite: false,
    image:
      'https://www.toysrus.com.my/dw/image/v2/BDGJ_PRD/on/demandware.static/-/Sites-master-catalog-toysrus/default/dwa8c1c415/e/3/1/1/e311b65108510def53ef3dab7e9925616d4dcb8a_934882_i1.jpg?sw=500&sh=500&q=75',
    description: 'High-speed racer car with sleek design and durable build.',
  },
  {
    id: 33,
    name: 'Mini Basketball Hoop Set',
    price: 700,
    category: 'Sports',
    categoryTag: 'best',
    rating: 4.4,
    isFavourite: false,
    image: 'https://media.prod.bunnings.com.au/api/public/content/7f371213564d422094c7d7569513521c',
    description: 'Portable basketball hoop set for kids to enjoy indoor games.',
  },
  {
    id: 34,
    name: 'Galactic Space Hero',
    price: 890,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://www.toyworld.co.nz/cdn/shop/files/F65885L00_combo_23_Online_1024SQ_7b8b4c0b-9a0c-408a-b39f-a33f7831e65f.jpg?v=1732148326',
    description: 'Action figure with space armor and laser blaster for adventures.',
  },
  {
    id: 35,
    name: 'Monster Truck Crusher',
    price: 1300,
    category: 'Cars',
    categoryTag: 'trending',
    rating: 4.7,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71ghrBwF-ML.jpg',
    description: 'Durable monster truck toy with big wheels for rough play.',
  },
  {
    id: 36,
    name: 'Kids Soccer Ball',
    price: 600,
    category: 'Sports',
    categoryTag: 'latest',
    rating: 4.3,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61AiR8UKDIL._UF894,1000_QL80_.jpg',
    description: 'Lightweight soccer ball perfect for kids learning to play.',
  },
  {
    id: 37,
    name: 'Ninja Stealth Fighter',
    price: 920,
    category: 'Action',
    categoryTag: 'best',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/6354836d1d058727dd282c1e-8-34-f-117-nighthawk-stealth.jpg',
    description: 'Stealthy ninja figure with weapons and martial arts moves.',
  },
  {
    id: 38,
    name: 'Classic Police Car',
    price: 1150,
    category: 'Cars',
    categoryTag: 'latest',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://rukminim2.flixcart.com/image/480/480/kfpq5jk0/vehicle-pull-along/7/e/w/set-of-2-police-car-truck-1-38-scale-diecast-police-car-lamb-original-imafw3ztrjz9fmky.jpeg?q=90',
    description: 'Toy police car with flashing lights and siren sounds.',
  },
  {
    id: 39,
    name: 'Junior Cricket Set',
    price: 850,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.4,
    isFavourite: false,
    image: 'https://funblast.in/cdn/shop/files/717nn-vxvDL._SL1500_1200x.jpg?v=1703837037',
    description: 'Fun cricket set with bat, ball, and stumps for kids.',
  },
  {
    id: 40,
    name: 'Robot Commander Action Figure',
    price: 980,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.7,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61iahSMxy7L._UF1000,1000_QL80_.jpg',
    description: 'Robotic action figure with lights and sound effects.',
  },
  {
    id: 41,
    name: 'Fire Rescue Truck',
    price: 1250,
    category: 'Cars',
    categoryTag: 'best',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://www.kheliyatoys.com/wp-content/uploads/2016/08/Centy-Fire-Tender-Pullback-Toy-Red-Die-Cast-Construction-Miniature-Fire-Rescue-Toy.webp',
    description: 'Toy fire truck with extendable ladder and water pump.',
  },
  {
    id: 42,
    name: 'Table Tennis Set',
    price: 750,
    category: 'Sports',
    categoryTag: 'latest',
    rating: 4.5,
    isFavourite: false,
    image: 'https://i.ibb.co/YZXb8Lb/tabletennis.jpg',
    description: 'Mini table tennis set for fun indoor matches.',
  },
  {
    id: 43,
    name: 'Samurai Action Hero',
    price: 940,
    category: 'Action',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://toycra.com/cdn/shop/files/Speed-Up-X-Stroke-Table-Tennis-Set-Outdoor-Toys-Speedup-Toycra-2_493x393.webp?v=1720627275',
    description: 'Samurai warrior action figure with katana and armor.',
  },
  {
    id: 44,
    name: 'Sports Car Racer',
    price: 1180,
    category: 'Cars',
    categoryTag: 'latest',
    rating: 4.7,
    isFavourite: false,
    image: 'https://baybee.co.in/cdn/shop/files/71vhzTarLDL.jpg?v=1745004095&width=1445',
    description: 'Sleek sports car toy with smooth wheels and glossy finish.',
  },
  {
    id: 45,
    name: 'Tennis Racket Set',
    price: 880,
    category: 'Sports',
    categoryTag: 'best',
    rating: 4.4,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61PTDGyakFS.jpg',
    description: 'Kids’ tennis racket set with soft balls for practice.',
  },
  {
    id: 46,
    name: 'Cyborg Warrior',
    price: 990,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.7,
    isFavourite: false,
    image:
      'https://www.shutterstock.com/image-illustration/scifi-mech-soldier-stands-attack-600nw-2581551597.jpg',
    description: 'Half-human half-machine figure with futuristic weapons.',
  },
  {
    id: 47,
    name: 'Rally Car Racer',
    price: 1100,
    category: 'Cars',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71Obqm0efoL._UF1000,1000_QL80_.jpg',
    description: 'Rugged rally car built for off-road racing fun.',
  },
  {
    id: 48,
    name: 'Kids Badminton Set',
    price: 720,
    category: 'Sports',
    categoryTag: 'latest',
    rating: 4.3,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/635d0cc992077a707e62d292-liberty-imports-badminton-set-for-kids.jpg',
    description: 'Complete badminton set for kids with rackets and shuttlecocks.',
  },
  {
    id: 49,
    name: 'Alien Invader Figure',
    price: 870,
    category: 'Action',
    categoryTag: 'best',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/63575de91592703f0c08d534-space-invaders-vinyl-blind-box.jpg',
    description: 'Alien action figure with glowing eyes and clawed hands.',
  },
  {
    id: 50,
    name: 'Classic Vintage Car',
    price: 1350,
    category: 'Cars',
    categoryTag: 'latest',
    rating: 4.8,
    isFavourite: false,
    image:
      'https://images-cdn.ubuy.co.in/667bb2493d11ff1b0f24f11e-classic-car-model-mini-household-toy.jpg',
    description: 'Stylish vintage car toy with retro detailing.',
  },
  {
    id: 51,
    name: 'Kids Basketball Set',
    price: 780,
    category: 'Sports',
    categoryTag: 'trending',
    rating: 4.4,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/61L23-G-0EL.jpg',
    description: 'Mini basketball set with hoop, ball, and stand.',
  },
  {
    id: 52,
    name: 'Gladiator Battle Figure',
    price: 910,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW_-XcMS6KBbj05GwEB954D3g-e9gBP_bNUA&s',
    description: 'Roman gladiator action figure with shield and sword.',
  },
  {
    id: 53,
    name: 'Rescue Ambulance Car',
    price: 1120,
    category: 'Cars',
    categoryTag: 'best',
    rating: 4.5,
    isFavourite: false,
    image: 'https://duckduckbaby.in/cdn/shop/files/DDB1430_1.jpg?v=1719612018',
    description: 'Ambulance toy with doors that open and light-up sirens.',
  },
  {
    id: 54,
    name: 'Table Football Game',
    price: 950,
    category: 'Sports',
    categoryTag: 'latest',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh_uIJnwGd7joaG6EVEwrLWhPiPjopg7aOIA&s',
    description: 'Mini foosball game for kids and family fun.',
  },
  {
    id: 55,
    name: 'Super Soldier Figure',
    price: 930,
    category: 'Action',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/81uvpkV7nNL.jpg',
    description: 'Brave super soldier figure with armor and shield.',
  },
  {
    id: 56,
    name: 'Dragster Racing Car',
    price: 1200,
    category: 'Cars',
    categoryTag: 'latest',
    rating: 4.7,
    isFavourite: false,
    image: 'https://i.ebayimg.com/images/g/6J0AAOSwn~xkTopx/s-l1200.jpg',
    description: 'Fast dragster car designed for thrilling races.',
  },
  {
    id: 57,
    name: 'Hockey Stick Set',
    price: 800,
    category: 'Sports',
    categoryTag: 'best',
    rating: 4.3,
    isFavourite: false,
    image:
      'https://rukminim2.flixcart.com/image/480/640/kw104nk0/stick/f/b/2/kids-hockey-stick-with-ball-birthday-gift-item-plastic-pack-of-2-original-imag8sztfmupdkum.jpeg?q=20',
    description: 'Kids’ hockey stick and ball set for sporty fun.',
  },
  {
    id: 58,
    name: 'Shadow Assassin Figure',
    price: 960,
    category: 'Action',
    categoryTag: 'latest',
    rating: 4.5,
    isFavourite: false,
    image:
      'https://fatcatcollectibles.in/cdn/shop/files/1_5000x_10fc5cad-121f-4403-b492-2ab46267e286.webp?v=1743849084&width=2048',
    description: 'Stealthy assassin figure with twin blades and hooded cape.',
  },
  {
    id: 59,
    name: 'Off-Road Jeep',
    price: 1280,
    category: 'Cars',
    categoryTag: 'trending',
    rating: 4.6,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/41t3o+aZFvL._UF1000,1000_QL80_.jpg',
    description: 'Sturdy off-road jeep toy built for adventure play.',
  },
  {
    id: 60,
    name: 'Kids Volleyball Set',
    price: 820,
    category: 'Sports',
    categoryTag: 'latest',
    rating: 4.4,
    isFavourite: false,
    image: 'https://m.media-amazon.com/images/I/71HWH1-fn8L.jpg',
    description: 'Fun volleyball set for kids with net and soft ball.',
  },
  {
    id: 61,
    name: 'Iron Knight Figure',
    price: 970,
    category: 'Action',
    categoryTag: 'best',
    rating: 4.6,
    isFavourite: false,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS9wInuO3S3X3-utilM-LPH7mMTeJWhi6QJQ&s',
    description: 'Knight in shining armor action figure with sword and shield.',
  },
]
